name = "tensorcode-cf-worker-stag"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "afeeea28ef4b58aad33f54322feaab68"

[[d1_databases]]
binding = "DB"
database_name = "tensorcode-db-stag"
database_id = "ffed4b8e-b83c-406e-9c22-fadac4a40294"

[vars]
# CLOUDFLARE_API_TOKEN = "your-secret-token" # Don't commit secret - use wrangler secret instead
